---

name: Build OpenEVSE firmware

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke workflow in OpenEVSE repo
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Build/Release OpenEVSE
          repo: OpenEVSE/ESP32_WiFi_V4.x
          ref: master
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "v2_ref": "${{ github.ref_name }}" }'
